Cronus/ViewModels/ApproverViewModel.cs
using DatabaseEntities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cronus.ViewModels
{
    public class ApproverViewModel
    {
        public IEnumerable<project> Projects { get; set; }
        public IEnumerable<activity> Activities { get; set; }
        public IList<employee> Employees { get; set; }
        public IList<employeetimeperiod> employeetimeperiods { get; set; }
        public ICollection<hoursworked> HoursWorkedList { get; set; }
        public timeperiod timeperiod { get; set; }
        public bool isApproved { get; set; }

    }
}

Cronus/Controllers/ApproverController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DatabaseEntities;
using Cronus.ViewModels;
using Cronus.Login;

namespace Cronus.Controllers
{
    public class ApproverController : Controller
    {
        private CronusDatabaseEntities db = new CronusDatabaseEntities();

        // GET: Approver
        public ActionResult Index()
        {
            TimePeriodViewModel model = new TimePeriodViewModel();
            List<timeperiod> timeperiod = db.timeperiods.ToList();

            timeperiod = timeperiod.OrderByDescending(d => d.periodEndDate).ToList();

            model.timePeriods = timeperiod.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.periodEndDateString.ToString(),
                    Value = a.periodEndDate.ToString()
                };
            });

            


            //loggedinEmp.employeeGroupManaged

            ViewBag.GroupId = UserManager.User.managesgroup;
            return View(model);

            //return View(db.timeperiods.ToList());
        }

        public ActionResult Approver_Index(int groupID, DateTime periodEnddate)
        {
            var perioudEndDateQuery = db.timeperiods.Find(periodEnddate);

            var groupQuery = db.groups.Find(groupID);

            int[] projectIds = groupQuery.projects.Select(x => x.projectID).ToArray();
            var projectsQuery = (from p in db.projects where (projectIds.Contains(p.projectID)) select p).ToList();

            string [] employeeIds = groupQuery.employees.Select(x => x.employeeID).ToArray();
            var employeeQuery = (from e in db.employees where (employeeIds.Contains(e.employeeID)) select e).ToList();

            // var timeperiods = db.timeperiods.ToArray();
            var employeeTimeperiods = (from et in db.employeetimeperiods where (et.TimePeriod_periodEndDate.Equals(periodEnddate) && employeeIds.Contains(et.Employee_employeeID)) select et).ToList();
            //var employeeTimeperiods = (from et in db.employeetimeperiods where (periodEnddate.Equals(et.TimePeriod_periodEndDate) && perioudEndDateQuery.employeetimeperiods.Select(e => e.Employee_employeeID).Contains(et.timeperiod)) select et).ToList();

            //getting the first timeperiod to test functionality. Dynamicism will be implemented later
            //timeperiod timeperiod = db.timeperiods.FirstOrDefault();

            ApproverViewModel approverViewModel = new ApproverViewModel();
            approverViewModel.Projects = projectsQuery;
            approverViewModel.Activities = db.activities.ToList();
            approverViewModel.HoursWorkedList = db.hoursworkeds.ToList();
            approverViewModel.Employees = employeeQuery;
            approverViewModel.timeperiod = perioudEndDateQuery;
            approverViewModel.isApproved = false;
            approverViewModel.employeetimeperiods = employeeTimeperiods.ToList();
            //approverViewModel.ActivityNames = new SelectList(myModel.Activities, "activityID", "activityName");

            return View(approverViewModel);
        }

        [HttpPost]
        public ActionResult ApproverIndex(ApproverViewModel approverViewModel)
        {
            if (ModelState.IsValid)
            {

                //if (project.activityIds != null)
                //{
                //    project.activities = (from s in this.activityRepository.All where project.activityIds.Contains(s.activityID) select s).ToList();
                //}
                foreach(employeetimeperiod employeetp in approverViewModel.employeetimeperiods)
                {
                    db.Entry(employeetp).State = EntityState.Modified;
                }
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(approverViewModel);


        }

        //// GET: Approver/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    project project = db.projects.Find(id);
        //    if (project == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(project);
        //}

        //// GET: Approver/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Approver/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "projectID,projectName,projectStartDate,projectEndDate,projectDescription,projectCapitalCode,projectAbbreviation,projectActive")] project project)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.projects.Add(project);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(project);
        //}

        //// GET: Approver/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    project project = db.projects.Find(id);
        //    if (project == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(project);
        //}

        //// POST: Approver/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "projectID,projectName,projectStartDate,projectEndDate,projectDescription,projectCapitalCode,projectAbbreviation,projectActive")] project project)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(project).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(project);
        //}

        //// GET: Approver/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    project project = db.projects.Find(id);
        //    if (project == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(project);
        //}

        //// POST: Approver/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    project project = db.projects.Find(id);
        //    db.projects.Remove(project);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cronus/Views/Approver/ApproverIndex.cshtml
@model Cronus.ViewModels.ApproverViewModel


@{
    ViewBag.Title = "ApproverIndex";
}

<h3>
    Approve hours for the time peried ending @Html.DisplayFor(modelItem => Model.timeperiod.periodEndDate)
</h3>

@using (Html.BeginForm())
{

    
    //&nbsp;
    //&nbsp;


    <h2> </h2>

    @Html.HiddenFor(modelItem => modelItem.isApproved)







    @*<script>
        $(function () {
            $("#accordion").accordion({ header: "h3", collapsible: true, active: false });
        });
    </script>*@
    <div class="demo">
        @{int i = 0;}
        
        @*@foreach (var employee in Model.Employees)*@
            @for (var j = 0; j < Model.Employees.Count; j++)
            {
                var employee = Model.Employees[j];

                @Html.HiddenFor(modelItem => modelItem.employeetimeperiods[j].Employee_employeeID)
                @Html.HiddenFor(modelItem => modelItem.employeetimeperiods[j].isApproved)
                @Html.HiddenFor(modelItem => modelItem.employeetimeperiods[j].TimePeriod_periodEndDate)

                @*@Html.HiddenFor(modelItem => modelItem.Employees[j].employeeID)
                @Html.HiddenFor(modelItem => modelItem.Employees[j].employeeLastName)
                @Html.HiddenFor(modelItem => modelItem.Employees[j].employeeFirstName)*@

                @*@Html.HiddenFor(modelItem => modelItem.Employees[j].employeetimeperiods.Select(e => e).Where(e => e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate).FirstOrDefault().Employee_employeeID)
                @Html.HiddenFor(modelItem => modelItem.Employees[j].employeetimeperiods.Select(e => e).Where(e => e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate).FirstOrDefault().TimePeriod_periodEndDate)*@



            @*<div class="panel-heading">
                        <strong>
                            @Html.DisplayFor(modelItem => employee.employeeFirstName) @Html.DisplayFor(modelItem => employee.employeeLastName)
                        </strong>
                    <div class="pull-right">
                            <label>Approved</label>
                            @Html.CheckBoxFor(modelItem => Model.timeperiod.isApprovedBool)
                    </div>
                </div>*@

            <h3 class="panel-title">
                <strong>
                    @*@Html.CheckBoxFor(modelItem => modelItem.Employees[j].employeetimeperiods.Select(e => e).Where(e => e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate).FirstOrDefault().isApproved)   @Html.DisplayFor(modelItem => employee.employeeFirstName) @Html.DisplayFor(modelItem => employee.employeeLastName)*@
                    @*@Html.CheckBoxFor(modelItem => modelItem.employeetimeperiods.Select(e => e).Where(e => e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate && e.Employee_employeeID == employee.employeeID).FirstOrDefault().isApproved)   @Html.DisplayFor(modelItem => employee.employeeFirstName) @Html.DisplayFor(modelItem => employee.employeeLastName)*@
                    @Html.CheckBoxFor(modelItem => modelItem.employeetimeperiods[j].isApproved)   @Html.DisplayFor(modelItem => employee.employeeFirstName) @Html.DisplayFor(modelItem => employee.employeeLastName)
                    

                </strong>
            </h3>

            <div class="panel panel-default">

                @foreach (var project in Model.Projects)
                {
                    @*<div id="accordion">*@

                    <div class="panel-group" id="accordion_@i">
                        <div class="panel panel-default" id="panel_@i">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a data-toggle="collapse" data-target="#collapseOne_@i" href="#collapseOne_@i">
                                        --Project @Html.DisplayFor(modelItem => project.projectName)--
                                    </a>
                                </h3>
                            </div>
                            <div id="collapseOne_@i" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>
                                                @Html.Label("Activity Name")
                                            </th>
                                            <th>
                                                @Html.Label("Hours logged")
                                            </th>
                                            <th>
                                                @Html.Label("Comment")

                                            </th>
                                            <th>
                                                @Html.Label("Entry Date")
                                            </th>
                                        </tr>

                                        @foreach (var activity in project.activities)
                                        {

                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => activity.activityName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => Model.HoursWorkedList.Select(e => e).Where(e => e.Activity_activityID == activity.activityID && e.Project_projectID == project.projectID && e.TimePeriod_employeeID == employee.employeeID && e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate).FirstOrDefault().hours)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => Model.HoursWorkedList.Select(e => e).Where(e => e.Activity_activityID == activity.activityID && e.Project_projectID == project.projectID && e.TimePeriod_employeeID == employee.employeeID && e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate).FirstOrDefault().comments)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => Model.HoursWorkedList.Select(e => e).Where(e => e.Activity_activityID == activity.activityID && e.Project_projectID == project.projectID && e.TimePeriod_employeeID == employee.employeeID && e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate).FirstOrDefault().date)
                                                </td>

                                            </tr>
                                        }

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    i++;
                }

            </div>

            

            }

        <div class="pull-right">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-default" />
                </div>
            </div>
        </div>


    </div>
            }




@*@Scripts.Render("~/bundles/modalform")*@

Cronus/Views/Approver/Approver_Index.cshtml
@model Cronus.ViewModels.ApproverViewModel


@{
    ViewBag.Title = "ApproverIndex";
}

<h3>
    Approve hours for the time period ending @Html.DisplayFor(modelItem => Model.timeperiod.periodEndDate)
</h3>

@*@if(Model.employeetimeperiods.Count() != Model.Employees.Count())
{
@:
    <script type="text/javascript">alert('Employees do not have times recorded for this timeperiod')</script>
}*@

@using (Html.BeginForm("ApproverIndex", "Approver"))
{


    //&nbsp;
    //&nbsp;


    <h2> </h2>

    @Html.HiddenFor(modelItem => modelItem.isApproved)

    <div class="demo">
        @{int i = 0;}

        @*@foreach (var employee in Model.Employees)*@
        @for (var j = 0; j < Model.employeetimeperiods.Count; j++)
        {
            var employee = Model.Employees[j];

            @Html.HiddenFor(modelItem => modelItem.employeetimeperiods[j].Employee_employeeID)
            @*@Html.HiddenFor(modelItem => modelItem.employeetimeperiods[j].isApproved)*@
            @Html.HiddenFor(modelItem => modelItem.employeetimeperiods[j].TimePeriod_periodEndDate)


            <h3 class="panel-title">
                <strong>
                    @Html.CheckBoxFor(modelItem => modelItem.employeetimeperiods[j].isApproved)   @Html.DisplayFor(modelItem => employee.employeeFirstName) @Html.DisplayFor(modelItem => employee.employeeLastName)
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    Total Hours:
                    @Html.Label(Model.HoursWorkedList.Select(e => e).Where(e => e.TimePeriod_employeeID == employee.employeeID && e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate).Sum(h => h.hours).ToString())
                </strong>
            </h3>


            <div class="panel panel-default">

                @foreach (var project in Model.Projects)
                {
                    @*<div id="accordion">*@

                    <div class="panel-group" id="accordion_@i">
                        <div class="panel panel-default" id="panel_@i">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a data-toggle="collapse" data-target="#collapseOne_@i" href="#collapseOne_@i">
                                        --Project @Html.DisplayFor(modelItem => project.projectName)--
                                        @*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*@
                                        <div style="float:right">
                                            Total Project Hours:
                                            @Html.Label(Model.HoursWorkedList.Select(e => e).Where(e => e.TimePeriod_employeeID == employee.employeeID && e.Project_projectID == project.projectID && e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate).Sum(h => h.hours).ToString())
                                        </div>
                                    </a>
                                </h3>
                            </div>
                            <div id="collapseOne_@i" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>
                                                @Html.Label("Activity Name")
                                            </th>
                                            <th>
                                                @Html.Label("Hours logged")
                                            </th>
                                            <th>
                                                @Html.Label("Comment")

                                            </th>
                                            <th>
                                                @Html.Label("Entry Date")
                                            </th>
                                        </tr>

                                        @foreach (var activity in project.activities)
                                        {
                                            var act = Model.HoursWorkedList.Select(e => e).Where(e => e.Activity_activityID == activity.activityID && e.Project_projectID == project.projectID && e.TimePeriod_employeeID == employee.employeeID && e.TimePeriod_periodEndDate == Model.timeperiod.periodEndDate);
                                            if (act != null && act.Count() != 0)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => activity.activityName)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => act.FirstOrDefault().hours)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => act.FirstOrDefault().comments)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => act.FirstOrDefault().date)
                                                    </td>

                                                </tr>
                                            }

                                        }

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    i++;
                }

            </div>



        }

        <div class="pull-right">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit" class="btn btn-default" />
                </div>
            </div>
        </div>


    </div>

            }


            





@*@Scripts.Render("~/bundles/modalform")*@

Cronus/Views/Approver/Create.cshtml
@model DatabaseEntities.project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.projectID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.projectID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.projectID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.projectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.projectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectStartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.projectStartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.projectStartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectEndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.projectEndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.projectEndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.projectDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.projectDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectCapitalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.projectCapitalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.projectCapitalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectAbbreviation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.projectAbbreviation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.projectAbbreviation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.projectActive, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.projectActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cronus/Views/Approver/Delete.cshtml
@model DatabaseEntities.project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.projectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectCapitalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectCapitalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectAbbreviation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectAbbreviation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectActive)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Cronus/Views/Approver/Details.cshtml
@model DatabaseEntities.project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.projectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectStartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectStartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectCapitalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectCapitalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectAbbreviation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectAbbreviation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.projectActive)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.projectID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Cronus/Views/Approver/Index.cshtml
@model   Cronus.ViewModels.TimePeriodViewModel


@{
    ViewBag.Title = "Index";
}

<h3>Pick a time period to approve hours</h3>


@using (Html.BeginForm("Approver_Index", "Approver", new { groupID = ViewBag.GroupId, periodEndDate = Model.periodEndDate}))
{
    <table>
        <tr>
            <td>
                @Html.DropDownListFor(n=>n.periodEndDate, Model.timePeriods, new { @class = "form-control", @style = "width: 300px;" })
            </td>
            <td>
                <input type="submit" , value="Submit", class="form-control", style = "width: 75px;" />
            </td>
        </tr>
    </table>
}




@*<table class="table">

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.periodEndDate)
        </td>
        <td>
            @Html.ActionLink("Select", "ApproverIndex", new { groupID = ViewBag.GroupId, periodEnddate = item.periodEndDate})
           
        </td>
    </tr>
}

</table>*@